# Generated by Django 4.2.4 on 2023-08-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.AddField(
            model_name='record',
            name='personal_account',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
