# Generated by Django 4.2.4 on 2023-08-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(default='in_progress', max_length=50, null=True),
        ),
    ]
