# Generated by Django 4.2.4 on 2023-08-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='responsilbe_person',
            new_name='responsible_person',
        ),
    ]
