# Generated by Django 4.2.4 on 2023-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_record_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
