# Generated by Django 4.2.4 on 2023-08-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_record_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50, null=True)),
                ('personal_account', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=255, null=True)),
                ('responsible_person', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(default='', max_length=50, null=True)),
                ('status', models.CharField(default='in_progress', max_length=50, null=True)),
            ],
        ),
    ]
